#!/usr/bin/env bash
#
# init-env.sh — generate a fresh .env with secure defaults.
#
# What it does:
#   - Generates SECRETS_KEY (32-byte hex) for at-rest secret encryption.
#   - Generates SESSION_SECRET (48-byte base64) for the admin cookie.
#   - Prompts for PUBLIC_URL (the URL GitHub will hit).
#   - Writes a complete .env file with sane defaults for everything else.
#
# Idempotent in spirit — refuses to clobber an existing .env unless you pass
# --force. With --force, the previous file is backed up to .env.bak.<timestamp>.
#
# Usage:
#   ./scripts/init-env.sh                         # interactive
#   ./scripts/init-env.sh --public-url=https://smee.io/abc \
#                         --reviewer-provider=claude \
#                         --non-interactive       # for CI / automation
#   ./scripts/init-env.sh --force                 # overwrite, backup existing

set -euo pipefail

ENV_FILE=".env"
FORCE=0
INTERACTIVE=1
PUBLIC_URL=""
ANTHROPIC_KEY=""
REVIEWER_PROVIDER="claude"

# ── Parse flags ──────────────────────────────────────────────────────────────
for arg in "$@"; do
  case "$arg" in
    --force)            FORCE=1 ;;
    --non-interactive)  INTERACTIVE=0 ;;
    --public-url=*)     PUBLIC_URL="${arg#*=}" ;;
    --anthropic-key=*)  ANTHROPIC_KEY="${arg#*=}" ;; # legacy API-key sandbox path
    --reviewer-provider=*) REVIEWER_PROVIDER="${arg#*=}" ;;
    -h|--help)
      sed -n '3,/^$/p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      printf "unknown flag: %s\n" "$arg" >&2
      exit 64
      ;;
  esac
done

# ── Helpers ──────────────────────────────────────────────────────────────────

# `random_hex N` → N hex chars from /dev/urandom (no openssl dependency).
random_hex() {
  local n="$1"
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "$((n / 2))"
  else
    # POSIX fallback. od + tr is slower but available everywhere.
    LC_ALL=C tr -dc 'a-f0-9' < /dev/urandom | head -c "$n"
    printf '\n'
  fi
}

# `random_b64 N` → ~N base64 chars from /dev/urandom.
random_b64() {
  local n="$1"
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 "$n"
  else
    head -c "$n" /dev/urandom | base64 | tr -d '\n='
    printf '\n'
  fi
}

prompt_default() {
  # Args: prompt-text default-value
  local p="$1" d="$2" answer
  if [ "$INTERACTIVE" -eq 0 ]; then
    printf "%s" "$d"
    return
  fi
  if [ -n "$d" ]; then
    printf "  %s [%s]: " "$p" "$d" >&2
  else
    printf "  %s: " "$p" >&2
  fi
  read -r answer </dev/tty
  printf "%s" "${answer:-$d}"
}

prompt_secret() {
  # Args: prompt-text — reads without echo. Empty allowed.
  local p="$1" answer
  if [ "$INTERACTIVE" -eq 0 ]; then
    printf ""
    return
  fi
  printf "  %s (input hidden, leave blank if unused): " "$p" >&2
  stty -echo
  read -r answer </dev/tty || true
  stty echo
  printf "\n" >&2
  printf "%s" "$answer"
}

# ── Refuse to clobber unless --force ─────────────────────────────────────────
if [ -f "$ENV_FILE" ] && [ "$FORCE" -ne 1 ]; then
  cat >&2 <<EOF

  ./$ENV_FILE already exists. Refusing to overwrite.

    Re-run with --force to back up the current file to .env.bak.<timestamp>
    and write a fresh one. Or edit it directly.

EOF
  exit 1
fi

if [ -f "$ENV_FILE" ]; then
  ts="$(date +%Y%m%d-%H%M%S)"
  backup=".env.bak.$ts"
  cp "$ENV_FILE" "$backup"
  printf "  backed up existing .env → %s\n" "$backup" >&2
fi

# ── Gather inputs ────────────────────────────────────────────────────────────
printf "\nGenerating .env\n\n" >&2

if [ -z "$PUBLIC_URL" ]; then
  PUBLIC_URL="$(prompt_default 'PUBLIC_URL (URL GitHub posts webhooks to)' 'http://localhost:3000')"
fi

if [ "$REVIEWER_PROVIDER" != "claude" ] && [ "$REVIEWER_PROVIDER" != "codex" ]; then
  printf "REVIEWER_PROVIDER must be 'claude' or 'codex'\n" >&2
  exit 64
fi

SECRETS_KEY="$(random_hex 64)"
SESSION_SECRET="$(random_b64 48)"

# ── Write the file ───────────────────────────────────────────────────────────
umask 077  # so .env is created mode 600 (readable only by you)
cat > "$ENV_FILE" <<EOF
# ─────────────────────────────────────────────────────────────────────────────
# GitHub Code Reviewer — generated by scripts/init-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
#
# Treat this file like a password. It contains the keys that decrypt the
# at-rest secrets in the SQLite database. \`umask 077\` was applied at write.
# ─────────────────────────────────────────────────────────────────────────────

NODE_ENV=production
PORT=3000
PUBLIC_URL=$PUBLIC_URL
DATABASE_PATH=/var/lib/gcr/data.sqlite

# 32-byte hex. Generated with: openssl rand -hex 32
SECRETS_KEY=$SECRETS_KEY

# Random ≥32 chars. Generated with: openssl rand -base64 48
SESSION_SECRET=$SESSION_SECRET

# Reviewer provider. Uses the local subscription-backed CLI login available to
# the worker process; no API key is needed for the default path.
REVIEWER_PROVIDER=$REVIEWER_PROVIDER
REVIEWER_TIMEOUT_MS=1200000

CLAUDE_CODE_BINARY=claude
CLAUDE_CODE_HOME=
CLAUDE_CODE_MODEL=claude-sonnet-4-5

CODEX_BINARY=codex
CODEX_HOME=
CODEX_MODEL=gpt-5-codex

# Legacy API-key sandbox path. Leave blank unless you re-enable it explicitly.
ANTHROPIC_API_KEY=$ANTHROPIC_KEY

# 'fatal' | 'error' | 'warn' | 'info' | 'debug' | 'trace'
LOG_LEVEL=info

# Legacy Docker sandbox setup
SANDBOX_DOCKER_HOST=unix:///var/run/docker.sock
SANDBOX_IMAGE=
SANDBOX_TIMEOUT_MS=1200000

# Prometheus
METRICS_BIND=127.0.0.1:9090

# OpenTelemetry tracing endpoint (optional). Tracing is initialized but
# disabled until this is set.
# OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4318

# Local-dev tunneling (optional). \`pnpm tunnel:ngrok\` prefers a host ngrok
# session at 127.0.0.1:4040 (e.g. \`ngrok http 3000 --domain=...\` you started
# yourself). The variables below are needed only if you let compose run
# ngrok for you.
#   Free tier auth token: https://dashboard.ngrok.com/get-started/your-authtoken
#   Reserved free-tier domain (stable URL): https://dashboard.ngrok.com/cloud-edge/domains
# NGROK_AUTHTOKEN=
# NGROK_DOMAIN=
EOF

chmod 600 "$ENV_FILE"

# ── Done ─────────────────────────────────────────────────────────────────────
cat >&2 <<EOF

  Wrote $ENV_FILE (mode 600)

  Next:
    1. Start compose: docker compose -f docker/compose.yml up -d --build
    2. Authenticate the reviewer inside the worker container.
    3. Open ${PUBLIC_URL}/setup to register the GitHub App.
    4. Verify with: pnpm smoke

EOF
