#!/usr/bin/env bash
#
# init-env.sh — generate a fresh .env with secure defaults.
#
# Usage:
#   ./scripts/init-env.sh                                 # interactive
#   ./scripts/init-env.sh --public-url=https://smee.io/abc
#                         --reviewer-provider=claude
#                         --non-interactive
#   ./scripts/init-env.sh --force                         # overwrite, backup

set -euo pipefail

ENV_FILE=".env"
FORCE=0
INTERACTIVE=1
PUBLIC_URL=""
REVIEWER_PROVIDER="claude"

for arg in "$@"; do
  case "$arg" in
    --force)            FORCE=1 ;;
    --non-interactive)  INTERACTIVE=0 ;;
    --public-url=*)     PUBLIC_URL="${arg#*=}" ;;
    --reviewer-provider=*) REVIEWER_PROVIDER="${arg#*=}" ;;
    -h|--help)
      sed -n '3,/^$/p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      printf "unknown flag: %s\n" "$arg" >&2
      exit 64
      ;;
  esac
done

random_hex() {
  local n="$1"
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "$((n / 2))"
  else
    LC_ALL=C tr -dc 'a-f0-9' < /dev/urandom | head -c "$n"
    printf '\n'
  fi
}

random_b64() {
  local n="$1"
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 "$n"
  else
    head -c "$n" /dev/urandom | base64 | tr -d '\n='
    printf '\n'
  fi
}

prompt_default() {
  local p="$1" d="$2" answer
  if [ "$INTERACTIVE" -eq 0 ]; then
    printf "%s" "$d"
    return
  fi
  if [ -n "$d" ]; then
    printf "  %s [%s]: " "$p" "$d" >&2
  else
    printf "  %s: " "$p" >&2
  fi
  read -r answer </dev/tty
  printf "%s" "${answer:-$d}"
}

if [ -f "$ENV_FILE" ] && [ "$FORCE" -ne 1 ]; then
  cat >&2 <<EOF

  ./$ENV_FILE already exists. Refusing to overwrite.

    Re-run with --force to back up the current file to .env.bak.<timestamp>
    and write a fresh one. Or edit it directly.

EOF
  exit 1
fi

if [ -f "$ENV_FILE" ]; then
  ts="$(date +%Y%m%d-%H%M%S)"
  backup=".env.bak.$ts"
  cp "$ENV_FILE" "$backup"
  printf "  backed up existing .env → %s\n" "$backup" >&2
fi

printf "\nGenerating .env\n\n" >&2

if [ -z "$PUBLIC_URL" ]; then
  PUBLIC_URL="$(prompt_default 'PUBLIC_URL (URL GitHub posts webhooks to)' 'http://localhost:3000')"
fi

if [ "$REVIEWER_PROVIDER" != "claude" ] && [ "$REVIEWER_PROVIDER" != "codex" ] &&
  [ "$REVIEWER_PROVIDER" != "acp" ]; then
  printf "REVIEWER_PROVIDER must be 'claude', 'codex', or 'acp'\n" >&2
  exit 64
fi

# Pick NODE_ENV based on PUBLIC_URL: localhost / smee → development, else production.
NODE_ENV="production"
case "$PUBLIC_URL" in
  http://localhost*|http://127.0.0.1*|https://smee.io/*) NODE_ENV="development" ;;
esac

SECRETS_KEY="$(random_hex 64)"
SESSION_SECRET="$(random_b64 48)"

umask 077
cat > "$ENV_FILE" <<EOF
# Generated by scripts/init-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Treat this file like a password — it contains the keys that decrypt the
# at-rest secrets in the SQLite database. umask 077 was applied at write.

NODE_ENV=$NODE_ENV
PORT=3000
PUBLIC_URL=$PUBLIC_URL
DATABASE_PATH=/var/lib/gcr/data.sqlite

# 32-byte hex. Generated with: openssl rand -hex 32
SECRETS_KEY=$SECRETS_KEY

# Random ≥32 chars. Generated with: openssl rand -base64 48
SESSION_SECRET=$SESSION_SECRET

# Reviewer provider. Uses the local subscription-backed CLI login available to
# the worker process; no API key is needed.
REVIEWER_PROVIDER=$REVIEWER_PROVIDER
REVIEWER_TIMEOUT_MS=1200000

CLAUDE_CODE_BINARY=claude
CLAUDE_CODE_HOME=
CLAUDE_CODE_MODEL=claude-sonnet-4-5

CODEX_BINARY=codex
CODEX_HOME=
CODEX_MODEL=gpt-5-codex

# Generic ACP reviewer (only used when REVIEWER_PROVIDER=acp or a repo
# overrides to "acp"). github-copilot runs \`copilot --acp\`; "custom"
# takes command/args from ACP_AGENT_COMMAND / ACP_AGENT_ARGS.
ACP_AGENT=github-copilot
ACP_AGENT_COMMAND=
ACP_AGENT_ARGS=
ACP_AGENT_HOME=
ACP_MODEL=

# 'fatal' | 'error' | 'warn' | 'info' | 'debug' | 'trace'
LOG_LEVEL=info

# Prometheus
METRICS_BIND=127.0.0.1:9090
EOF

chmod 600 "$ENV_FILE"

cat >&2 <<EOF

  Wrote $ENV_FILE (mode 600, NODE_ENV=$NODE_ENV)

  Next:
    1. docker compose -f docker/compose.yml up -d --build
    2. open ${PUBLIC_URL}/setup
    3. authenticate the reviewer CLI inside the worker container

EOF
